[theme]
base = "light"
primaryColor = "#f0a500"
backgroundColor = "#f4f6f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#1A1A2E"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
